{{- if ne .Values.env "local" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-map-appconfig
data:
  application-config.yaml: |-
{{ tpl ( .Files.Get "application-config.yaml" ) . | printf "%s" | indent 4 }}
{{- end }}
{{- if eq .Values.env "local" }}
{{ tpl ( .Files.Get "application-config.yaml" ) . | printf "%s" }}
{{- end }}

