{{- if .Values.route.enabled }}
{{- $fullName := include "infra.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{ end }}
